services:
  - type: web
    name: salphaevnj
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: 'off'

  - type: web
    name: sbetaiiwr
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: 'off'

  - type: web
    name: sdelta8t2d
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: 'off'

  - type: web
    name: salphajb7j
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: 'off'

  - type: web
    name: sgammano54
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: 'off'

  - type: web
    name: sneoniyfo
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: 'off'

  - type: web
    name: sgammah9xm
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: 'off'

  - type: web
    name: sbetaxhss
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: 'off'

  - type: web
    name: sneonppe1
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: 'off'

  - type: web
    name: szincekmn
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: 'off'

  - type: web
    name: sio243f
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: 'off'

  - type: web
    name: sgammagqhr
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: 'off'

  - type: web
    name: sgamma5kgq
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: 'off'

  - type: web
    name: sneon25ej
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: 'off'

  - type: web
    name: sneonks8a
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: 'off'

